### ISSUE TITLE
WP plugin activation

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#1]
When activating this plugin there is a WP error:

> The plugin generated 713 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

Which plugin did you try to install? You need to extract the Extended zip file and then zip each plugin that you need for your site. Please see the installation: https://github.com/ultimatemember/Extended#installation

Regards,

**Comment by champsupertramp** [comment]
I'm planning on merging all these plugins as a centralized free plugin with lots of features

**Comment by MissVeronica** [comment]
I have the "Ultimate Member - Generate Dummy Accounts" plugin

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

Are you still having issues when installing the Generate Dummy Accounts plugin? I couldn't reproduce the issue on my end.

Regards,

**Comment by MissVeronica** [comment]
Also I got this PHP error:

wp-includes/functions.php:5401

> class-phpmailer.php is deprecated since version 5.5.0! Use wp-includes/PHPMailer/PHPMailer.php instead. The PHPMailer class has been moved to wp-includes/PHPMailer subdirectory and now uses the PHPMailer\PHPMailer namespace.>

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

Thanks for letting me know. I've pushed an update to this repo.  Please see:
https://github.com/ultimatemember/Extended/commit/5a0e8b604200bccc1b141f3dd965d2974b5947d0

Regards,

**Comment by champsupertramp** [comment]
Thanks for letting me know and for your help with the testing.
