### ISSUE TITLE
how to edit the Vcard Icon, and add more specific fields to the vcf file Resolved

### ISSUE THREAD

**Issue by medAnnas** [ultimatemember/Extended#16]
Hello,

I want to edit the ” um-faicon-file-o ” Icon, I checked the function.php but it's not there, I found only the label icon, and please how can the vcf file contain the website field? company name etc .. ? now it contains the phone number, the name, and the profile picture

Thank you

**Comment by champsupertramp** [comment]
Hi @champsupertramp  We are using this vendor https://github.com/jeroendesloovere/vcard/

It appears the Organization property is still not supported.
https://github.com/jeroendesloovere/vcard/tree/2.0.0-dev#organizational-properties
