### ISSUE TITLE
Extended/um-user-shortcode

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#2]
Replace `get_current_user_id()` with `um_profile_id()` two times and this shortcode will be OK.

Current version of the code snippet will display the visiting user's meta value instead of the meta value from the visited user profile.

**Comment by champsupertramp** [comment]
Hi @MissVeronica 

This has been changed. Please see: https://github.com/ultimatemember/Extended/commit/7969535fe43e349d6394a7a1423c318dcb4969bb

Thank you for your suggestions.

Regards,
