### ISSUE TITLE
VCard problem with the phone field

### ISSUE THREAD

**Issue by medAnnas** [ultimatemember/Extended#20]
Hello, when I tried to import a contact the " tel " word appeared with the numbers what cause the problem how I can solve this?

**Comment by medAnnas** [comment]
any update or solution for this problem ?

**Comment by MissVeronica** [comment]
You can edit this file:

`../plugins/um-vcard/vendor/jeroendesloovere/vcard/src/Formatter/Property/TelephoneFormatter.php`

and in the line 23 remove `tel:`

**Comment by medAnnas** [comment]
Thank you for your help, it works!
