### ISSUE TITLE
Big Profile photos not cropping correctly - um-profile-photo

### ISSUE THREAD

**Issue by pkanel80** [ultimatemember/Extended#21]
Issue regarding extension "Enable Profile Photo in Register form" - um-profile-photo 
When users uploading profile photo that is a little bit bigger than normal, then the cropping is not working correctly. 
For example check the attached screenshots where the upload profile photo has dimensions 2252x4000, but as you can see crop is not working. 
The only active plugin is ultimate-member

Initial upload & crop selection:  https://ibb.co/PFx2HCz
After Crop: https://ibb.co/vsjGFPs

**Comment by MissVeronica** [comment]
This might be a PHP memory size issue.
Look at all points in this guide
https://docs.ultimatemember.com/article/114-photo-uploads-not-working

**Comment by pkanel80** [comment]
Hi MissVeronica, do you any other (demo) sites that have profile photo in registration to check if it's working?

**Comment by MissVeronica** [comment]
Now I have made a test uploading a picture with the size 5312 x 2988 ( 4,19 MB ) without issues.
Your issue is with a picture size of 2252×4000.

Look in your browser's web console if you have any JavaScript errors as the cropping is made by JavaScript.

If no JavaScript errors enable PHP debug logging:
https://docs.ultimatemember.com/article/1751-enable-debug-logging

You will probably get a PHP log file with notices and errors in `/wp-content/debug.log` when you do a picture upload.
Post the content of this file here and we can give you a PHP error explanation.

**Comment by pkanel80** [comment]
Thanks for your prompt response. I have enabled the debug logs. I can't see any errors. 
Only the following which I believe is irrelevant because I see it in every page load. 

"VM2729 js:51          POST https://region1.google-analytics.com/g/collect?v=2&tid=G-LC0EVQZLR1&gtm=45je3360&_p=142219104&gdid=dZGIzZG&cid=1179477344.1677872469&ul=en-gb&sr=3440x1440&uaa=x86&uab=64&uafvl=Chromium%3B110.0.5481.180%7CNot%2520A(Brand%3B24.0.0.0%7CGoogle%2520Chrome%3B110.0.5481.180&uamb=0&uam=&uap=Windows&uapv=15.0.0&uaw=0&_s=7&sid=1678541967&sct=7&seg=1&dl=https%3A%2F%2Fwww.themodel.gr%2Fregister%2F&dr=https%3A%2F%2Fwww.themodel.gr%2F&dt=Registration%20-%20The%20Model&en=click&ep.forceSSL=true&ep.link_attribution=true&ep.link_id=&ep.link_classes=um-modal-btn%20um-finish-upload%20image&ep.link_url=javascript%3Avoid(0)%3B&ep.link_domain=&ep.outbound=true&_et=5841 net::ERR_BLOCKED_BY_CLIENT"

Do you want to make a try?
the page is the following: https://www.themodel.gr/register/
the image is the following: https://ibb.co/MfNgnBP

BR/Panos

**Comment by MissVeronica** [comment]
I downloaded your picture and made a test at my site without any issues.

Can you post here your `UM Settings -> Install Info`

**Comment by pkanel80** [comment]
sure, find attached --> [https://easyupload.io/zny6i0](url)
let me note that I have already tried to disable all other plugins or change theme. 
still the same issue from any browser (chrome, firefox, opera).

**Comment by MissVeronica** [comment]
You have a Theme JavaScript error on your Registration page

```
Uncaught TypeError: $(...).owlCarousel is not a function
    <anonymous> https://www.themodel.gr/wp-content/themes/talenthunt/js/custom.js?ver=81582bdb254a94e4464424087c6479a8:110
    <anonymous> https://www.themodel.gr/wp-content/themes/talenthunt/js/custom.js?ver=81582bdb254a94e4464424087c6479a8:159
```

Change to a WP default theme like "Twenty Twenty-Two"

For the PHP Debug error can you deactivate the Google Analytics plugin.

I found that you have the UM "User Photos" Extension can you deactivate that plugin.

**Comment by MissVeronica** [comment]
Increase memory to at least 512MB to follow Elementor guidelines:

https://elementor.com/help/requirements/

> WP Memory limit of 256 MB (Elementor and Elementor Pro only), 512 MB recommended, 768 MB for best performance. 
Note: These requirements are for Elementor. If you are using additional plugins on your site that also have minimum requirements such as WooCommerce, you may need to increase your memory to 512 MB to help avoid loading issues.

**Comment by pkanel80** [comment]
Changed to default wordpress theme in dev environment and disabled all plugins except UM and register profile photo (with debug logs). Still the same issue :/  
Link:  https://uat.themodel.gr/register/

I think I found the issue. 
With image resolution 4000x2252 everything is working correctly. --> https://ibb.co/HP1MLjx
With image resolution 2252x4000 I can reproduce the issue, so I guess it's about the resolution and the height. --> https://ibb.co/MfNgnBP

**Comment by MissVeronica** [comment]
I made a profile upload with resolution 2252x4000 without any issues so it's your site that have the issue.

**Comment by pkanel80** [comment]
> I made a profile upload with resolution 2252x4000 without any issues so it's your site that have the issue.

and the crop worked correctly? for example you tried to upload the same picture and crop down-left area and everything worked as expected? Can you please provide me the url to also make a try?

**Comment by MissVeronica** [comment]
After uploading the cropped picture

https://imgur.com/a/wjDldSu

**Comment by pkanel80** [comment]
this is a video of how I reproduce it. I also increased memory to maximum, nothing changed. 
Now are with all plugins disabled and default wp theme. 

https://screenrec.com/share/QYpKovAqwW

**Comment by MissVeronica** [comment]
Still your issue maybe your browser settings?

The second uploaded screen copy https://imgur.com/a/wjDldSu

**Comment by MissVeronica** [comment]
I made the same test upload with Chrome and it's working OK also with lower left corner cropped from the picture.

**Comment by pkanel80** [comment]
it can't be the browser settings. Tried from all of them, and the issue has been reported from visitors. 
I also deleted UM plugin with all settings / folder and installed it again from scratch. Issue still here.
I am out of ideas what else to try.

**Comment by pkanel80** [comment]
the issue remains if I also try another setting in the relevant field like: crop and force user-defined ratio: 
![image](https://user-images.githubusercontent.com/115407476/224498371-0c11d61d-0686-41e6-907a-c830b82b2c3c.png)

Only if I disable the crop the photo is ok.

**Comment by MissVeronica** [comment]
An issue with your Greek internet provider?
Your Web hosting/CDN connection to your Greek internet.
I'm connected from Sweden.

**Comment by pkanel80** [comment]
I also tried this with mobile phone which is different provider. haha :)

**Comment by pkanel80** [comment]
just a question. you tried on this link and it's working? https://uat.themodel.gr/register/

**Comment by MissVeronica** [comment]
Yes it's working this 3rd screen copy from Chrome: https://imgur.com/a/wjDldSu

**Comment by pkanel80** [comment]
Ok maybe I found something. Everytime I load the image for croping I don't have error but I have the following warning:

><html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="https://uat.themodel.gr/wp-includes/js/jquery/jquery.js?ver=3.6.1:5282" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">jquery.js?ver=3.6.1:5282</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-warning-text-color);">[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">https://www.chromestatus.com/feature/5745543795965952</span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | add | @ | jquery.js?ver=3.6.1:5282
-- | -- | -- | --
  | jQuery.event.add | @ | jquery-migrate.js?ver=3.3.2:642
  | (anonymous) | @ | jquery.js?ver=3.6.1:5182
  | each | @ | jquery.js?ver=3.6.1:385
  | each | @ | jquery.js?ver=3.6.1:207
  | on | @ | jquery.js?ver=3.6.1:5181
  | on | @ | jquery.js?ver=3.6.1:5906
  | addListeners | @ | um-crop.js?ver=2.5.4:338
  | build | @ | um-crop.js?ver=2.5.4:257
  | (anonymous) | @ | um-crop.js?ver=2.5.4:185
  | fn | @ | jquery.js?ver=3.6.1:5175
  | dispatch | @ | jquery.js?ver=3.6.1:5430
  | elemData.handle | @ | jquery.js?ver=3.6.1:5234

</span></div>
</body>
</html>

--------------------

**I asked chatgpt what is the meaning. Check the last paragraph:**

_This message is a browser console warning called a "violation" that occurred in the jQuery library. Specifically, it is a warning related to the use of an event listener on a touch device that may cause a delay or "blocking" of the scrolling action.

The warning suggests that the event listener should be marked as "passive" to improve the responsiveness of the page. Passive event listeners allow the browser to handle scrolling events more efficiently, without waiting for the listener to finish executing before taking action.

The warning includes a link to a page on Chrome's feature status site that provides more information about the passive event listener feature.

In this case, the warning is being triggered by the "um-crop.js" script, which is using the jQuery library to add event listeners to a touch device. The "addListeners" function in the script is where the event listeners are being added.

**To resolve the warning, the event listeners in the "um-crop.js" script should be updated to include the "passive: true" option when adding touch event listeners. This will help to improve the performance and responsiveness of the page on touch devices.**_

**Comment by MissVeronica** [comment]
OK There is no `passive: true` in the `um-crop.js`.
Can you test without touch option enabled?
My screen is a non-touch unit.

**Comment by pkanel80** [comment]
my screen is also non-touch unit. :/

**Comment by pkanel80** [comment]
Let me note that I have also the same issue when I change the profile photo on an existing account, not just the register screen.
With image resolution 4000x2252 everything is working correctly.
With image resolution 2252x4000 no.
with lower resolutions also ok.

**Comment by pkanel80** [comment]
I make full tests. an image with resolution 2252x4000 in png is working. 
in jpg and the same resolution I tried 3-4 photos and all of them are not working.
I also tried to upload a cover photo and I had the same results. in png all ok, in jpg for these specific resolution the same issue.

**Comment by MissVeronica** [comment]
I'm using Windows 10
Your UM Install Info says also Windows 10 Right?

**Comment by champsupertramp** [comment]
Please let us know if you're still encountering issues with the latest version. We'd be happy to help
