### ISSUE TITLE
Set password on activation mail issue

### ISSUE THREAD

**Issue by domov44** [ultimatemember/Extended#22]
Hi,

I put this shortcode {set_password_link} in my <a> in activation mail.

But the link doesn’t work, it’s looks great on the preview but when i tested the activation mail the button wasn’t clickable.

BTW : 
- i followed the step here : https://docs.ultimatemember.com/article/1693-set-password-on-email-activation
- I tested with the shortcode {password} and didn't work

Thanks for all

![image](https://user-images.githubusercontent.com/102806074/223680613-1b802abf-fc2d-4d8b-aad9-135b7fdb6b12.png)

![image](https://user-images.githubusercontent.com/102806074/223679397-0e62af49-0039-4647-b971-bb37f6b91c7c.png)

**Comment by ashubawork** [comment]
Hello @domov44 

I checked this issue and I haven't it. All works perfectly.
Try to switch mail editor to "text" and check your link. Paste the {set_password_link} shortcode to the href attribute.
![1679481094563](https://user-images.githubusercontent.com/43743394/226876381-3550d781-3944-4f1f-a877-816e42fbe3ad.jpg)

Regards.

**Comment by domov44** [comment]
Hi, just did it before and i retried today : it doesn't work 

![image](https://user-images.githubusercontent.com/102806074/226936407-dd03464d-59ed-4a63-b609-828d71f9624f.png)

Result, i can't click, the link is as if he wasn't there, select cursor on the button 
![image](https://user-images.githubusercontent.com/102806074/226937015-f6af93c7-d0d7-453e-a1c2-c3cafdaba6ac.png)

Have a good day

**Comment by domov44** [comment]
Hi, there is the HTML code for the link : 
<div style="padding: 10px 0 50px 0;text-align: center"><strong><a style="border: 2px solid #151B49;border-radius: 8px;background: #66cc99;color: #151b49;padding: 12px 30px;text-decoration: none;letter-spacing: 0.3px" href="{set_password_link}">Activer mon compte</a></strong></div>

From the received email, there is no href, so i can't clic on the link, look the source code : 
![image](https://user-images.githubusercontent.com/102806074/228020809-2b40641d-e940-4a93-98fe-58f351ca31f8.png)

Thx

**Comment by domov44** [comment]
I tested without div : 
<a href="{set_password_link}">test</a>

Same issue

**Comment by ashubawork** [comment]
Hi @domov44 

Could you check google mail or some other mail services just for testing?

Regards.

**Comment by domov44** [comment]
Hi, 
I tested and same issue here, no href and cursor text on button hover.
Thx

**Comment by champsupertramp** [comment]
Please let us know if you're still encountering issues with the latest version. We'd be happy to help

**Comment by domov44** [comment]
Hi sorry I was on other projects, so I retested and I have the same result
I've created a test user, I've put him on hold for confirmation and asked him to send me the UM confirmation email, I've received it but I still can't click on the link

![image](https://github.com/ultimatemember/Extended/assets/102806074/5297efff-c483-4217-953e-4ec752e09cd5)
![image](https://github.com/ultimatemember/Extended/assets/102806074/8dc0ef45-be08-41eb-850c-b7c25271b8d0)

**Comment by domov44** [comment]
Update : 
I uninstalled the plugin and reinstalled the set_password zip and it works.
