### ISSUE TITLE
Venezuela and Dominican Republic flags not showing up. Extension: Country flags

### ISSUE THREAD

**Issue by misterqam** [ultimatemember/Extended#24]
Venezuela and Dominican Republic flags not showing up, on website in Spanish. They don't show up either on their profile or the members directory. 

The problem has started recently -1 or 2 weeks-  for all users who have set Venezuela or Dominican Republic as their country on their profiles. Flags for other countries show up normally.

**Comment by ashubawork** [comment]
Hello @misterqam 

I checked the country flags for Venezuela and Dominican Republic and all works well. Please see my screenshots:
![2](https://user-images.githubusercontent.com/43743394/226865975-682975b8-8028-4478-b4e8-00c6a927ec38.jpg)
![1](https://user-images.githubusercontent.com/43743394/226865935-bc3e412f-6978-47f4-9b5d-854d688e27c6.jpg)

The flags are the pseudo elements from CSS. Maybe there are conflicts with other CSS on your site. Try to do a conflict test and check again - https://docs.ultimatemember.com/article/96-how-to-do-a-plugin-theme-conflict-test.

**Comment by champsupertramp** [comment]
Please let us know if you're still encountering issues with the latest version. We'd be happy to help
