### ISSUE TITLE
Delete users awaiting confirmation

### ISSUE THREAD

**Issue by f-riente** [ultimatemember/Extended#29]
Hello,

I have installed the plugin um-cron-delete following the instruction available here:

https://docs.ultimatemember.com/article/1670-schedule-user-deletions-with-wp-cronjob

1. downloaded the repository
2. zipped the plugin um-cron-delete
3. installed into wordpress
4. installed the WP Crontrol plugin that is supposed to run the job every day

However, I after several weeks I still have thousand of spam users not been deleted. Do you know what could be the issue?
I have also tried running the cronjob manually, going into Wordpress->Settings->Cron Schedules, and pressing "Run now" on the `um_cron_delete_users_cron`, but it doesn't have any effect.

I'm running ultimate member 2.6.3.

Best,

**Comment by champsupertramp** [comment]
Hi @f-riente  @davidvidovic-web  - This has been fixed and improved in the latest version:
https://github.com/ultimatemember/Extended/releases
