### ISSUE TITLE
Vcard - Problem 28/8/23

### ISSUE THREAD

**Issue by FotisVnm** [ultimatemember/Extended#32]
Dear @MissVeronica , 

I would like to report some issues regarding Vcard, which I would kindly request your guidance & assistance.

Issues :
1) When a user updates his information, i.e. phone number, and downloads the Vcard, then the Vcard will not provide the updated information, but the old ones.

2) When the Vcard is downloaded the only information that gets saved to the Vcard is "name/surname and Home number ". Emails and mobile phone number are missing.

Question:
- Is it possible for the aforementioned issues to be solved?
- If I wanted the Vcard to save more information, like a secondary email or a secondary phone number or any other information (such as business name etc), how can I change the code so that it would be possible ?! 

Thank you so much for taking the time to review my issues and questions.

Kind Regards,

Fotis

**Comment by champsupertramp** [comment]
Hi @FotisVnm 

Thank you for contacting us.

Are you using the latest release?
https://github.com/ultimatemember/Extended/releases

Kindest Regards,

**Comment by FotisVnm** [comment]
Hello @champsupertramp

Yes I'm using the latest release!

Thank you

**Comment by FotisVnm** [comment]
Dear @champsupertramp
Hello, 
I would like to know if you have any updates on my previous message. 

Thanks in advance.

**Comment by jeroendesloovere** [comment]
Hi @FotisVnm and @champsupertramp,

Nice to see that my vcard library is being used across the world.
For an answer on the questions, you can check out example code of the vcard library over here: https://github.com/jeroendesloovere/vcard/blob/v1.7.4/examples/example.php

**Comment by jeroendesloovere** [comment]
Ok that was documentation for the older version 1.7.4.
But the library which is being used is 2.0.0 (experimental version), example code can be found over here: https://github.com/jeroendesloovere/vcard/blob/2.0.0-dev/tests/VCardTest.php#L59

**Comment by champsupertramp** [comment]
Hi @FotisVnm 

Sorry for the delay as we were refactoring the extended plugin. Could you please try the latest release in the link?
https://github.com/ultimatemember/Extended/releases

Kindest Regards,
