### ISSUE TITLE
Uncaught error on um-block-emails

### ISSUE THREAD

**Issue by tridentmarketinguk** [ultimatemember/Extended#33]
Hey guys,

I'm just installing the Block Emails extension but as soon as I try to install it, I get this error.

Ultimate Member 2.6.11 currently installed.

Can anyone point me int he right direction of what im doing wrong please?

`Fatal error: Uncaught Error: Class "UM_Extended_Block_Emails\Core" not found in /var/www/vhosts/funeralsuppliers.uk/httpdocs/wp-content/plugins/um-block-emails/um-block-emails.php:102 Stack trace: #0 /var/www/vhosts/funeralsuppliers.uk/httpdocs/wp-content/plugins/um-block-emails/um-block-emails.php(108): um_extended_blockemails_plugin() #1 /var/www/vhosts/funeralsuppliers.uk/httpdocs/wp-admin/includes/plugin.php(2318): include_once('...') #2 /var/www/vhosts/funeralsuppliers.uk/httpdocs/wp-admin/plugins.php(192): plugin_sandbox_scrape() #3 {main} thrown in /var/www/vhosts/funeralsuppliers.uk/httpdocs/wp-content/plugins/um-block-emails/um-block-emails.php on line 102`

**Comment by champsupertramp** [comment]
Hi @tridentmarketinguk  Could you please try the pre-release version?https://github.com/ultimatemember/Extended/releases/tag/2.0.0-alpha2

**Comment by champsupertramp** [comment]
Hi @tridentmarketinguk  This has been fixed in the latest release:
https://github.com/ultimatemember/Extended/releases
