### ISSUE TITLE
UM Extended 2.0 failures

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#38]
Installation via WP of the plugin "UM Extended 2.0" 
will be reported by WP Plugins as "Ultimate Member - Extended Features & Functionalities" version 1.0.3

Clicking on "UM Extended" in the side bar and then attempt to enter anything in the textbox 
will terminate after first character with an empty blank page.

**Comment by MissVeronica** [comment]
```
Uncaught SyntaxError: redeclaration of const qm
    <anonymous> https://xxxxxxxxx/wp-admin/admin.php?page=um-extended#/:1118
[admin.php:1118:32](https://xxxxxxxxx/wp-admin/admin.php?page=um-extended#/)
    <anonymous> https://xxxxxxxxx/wp-admin/admin.php?page=um-extended#/:1118

Uncaught (in promise) TypeError: a.data.data is undefined
    load_extensions https://xxxxxxxxx/wp-content/plugins/Extended-2.0.0-alpha2/dist/assets/settings-4170bc27.js?ver=1.0.0:10
[settings-4170bc27.js:10:12168](https://xxxxxxxxx/wp-content/plugins/Extended-2.0.0-alpha2/dist/assets/settings-4170bc27.js?ver=1.0.0)
```

**Comment by champsupertramp** [comment]
Hi @MissVeronica  Thank you. This has been fixed in the new beta release:
https://github.com/ultimatemember/Extended/releases/tag/2.0.0-beta2

I've also updated the version number. 

Kindest Regards,

**Comment by MissVeronica** [comment]
OK 
Now I got the list of Plugins but when looking at the "Math Captcha in Register form" plugin it was version 1.0.1 and when trying to activate I got
`Invalid Class Name: UM_Extended_Math_Captcha\Core`

The old plugin "Math Captcha in Register form" was installed but deactivated.
I made a FTP delete of this plugin but still the `Invalid Class Name: UM_Extended_Math_Captcha\Core`

I made a FTP delete of "Extended-2.0.0-beta2." plugin to get WP active again.

Made a second install of "Extended-2.0.0-beta2." plugin and again the message 
`Invalid Class Name: UM_Extended_Math_Captcha\Core`
and now with a stack trace 

```
This message was triggered by Extended-2.0.0-beta2.

Call stack:

    wp_die()
    wp-content/plugins/Extended-2.0.0-beta2/um-extended.php:181
    UM_Extended->um_extended_construct()
    wp-content/plugins/Extended-2.0.0-beta2/um-extended.php:121
    UM_Extended::instance()
    wp-content/plugins/Extended-2.0.0-beta2/um-extended.php:214
    um_extended_plugin()
    wp-content/plugins/Extended-2.0.0-beta2/um-extended.php:216
    plugin_sandbox_scrape()
    wp-admin/includes/plugin.php:663
    activate_plugin()
    wp-admin/plugins.php:58
```
Now I will FTP delete the "Extended-2.0.0-beta2." plugin and no further testing.

**Comment by champsupertramp** [comment]
Hi @MissVeronica  Thank you. We've found the issue with the release files. It doesn't have the compiled vendors. We are fixing the Github actions now to resolve this issue. I'll get back to you

**Comment by champsupertramp** [comment]
Hi @MissVeronica  We've fixed the issue with the Github workflow. Vendors are now added to the release tags:

https://github.com/ultimatemember/Extended/releases/tag/2.0.0

Kindest Regards,

**Comment by MissVeronica** [comment]
Thanks.

Some issues during installation of the Extended-2.0.0 zip file

`The plugin generated 213 characters of unexpected output during activation.`
`Creation of dynamic property UM_Extended::$math_captcha is deprecated`
```
    wp-content/plugins/Extended-2.0.0/um-extended.php:194
    UM_Extended->add_method()
    wp-content/plugins/Extended-2.0.0/um-extended.php:167
    UM_Extended->um_extended_construct()
    wp-content/plugins/Extended-2.0.0/um-extended.php:121
    UM_Extended::instance()
    wp-content/plugins/Extended-2.0.0/um-extended.php:213
    um_extended_plugin()
    wp-content/plugins/Extended-2.0.0/um-extended.php:215
```

**Comment by MissVeronica** [comment]
Trying to activate some of the plugins with PHP 8.2.11

```
[07-Nov-2023 15:21:35 UTC] PHP Deprecated:  Creation of dynamic property UM_Extended::$block_emails is deprecated in .../wp-content/plugins/Extended-2.0.0/um-extended.php on line 194
[07-Nov-2023 15:21:53 UTC] PHP Deprecated:  Creation of dynamic property UM_Extended::$browser_detect is deprecated in .../wp-content/plugins/Extended-2.0.0/um-extended.php on line 194
[07-Nov-2023 15:22:08 UTC] PHP Deprecated:  Creation of dynamic property UM_Extended::$country_flag is deprecated in .../wp-content/plugins/Extended-2.0.0/um-extended.php on line 194
[07-Nov-2023 15:22:28 UTC] PHP Deprecated:  Creation of dynamic property UM_Extended::$cover_photo is deprecated in .../wp-content/plugins/Extended-2.0.0/um-extended.php on line 194
[07-Nov-2023 15:22:41 UTC] PHP Deprecated:  Creation of dynamic property UM_Extended::$math_captcha is deprecated in .../wp-content/plugins/Extended-2.0.0/um-extended.php on line 194
```

**Comment by MissVeronica** [comment]
UM Support Forum issue with blank page

https://wordpress.org/support/topic/um-extended-blank-page-after-installation/

**Comment by MissVeronica** [comment]
https://www.2euros.org/images/blankpage2.png

**Comment by champsupertramp** [comment]
Hi @MissVeronica  - We've released version 2.0.1 with fixes to this issue. Please let us know if you're still encountering any issues. Thank you

**Comment by Phobos94** [comment]
Hello,
I installed version 2.0.1 and I still have the same problem... :(

**Comment by MissVeronica** [comment]
Thanks

I downloaded and installed version 2.0.1 from https://github.com/ultimatemember/Extended/releases/tag/2.0.1

**Activation issue:** WP Installation did not replace version 2.0.0 beta1 which gave me a "Fatal error can't redeclare function ...."
WP Deactivate and WP Delete of version 2.0.0 beta1 fixed this issue.

Trying to Activate all plugins one by one failed with `Invalid Class Name: UM_WPCLI\Core` 
for one plugin the last one being activated.
`[13-Nov-2023 18:32:30 UTC] PHP Warning:  include(.../wp-content/plugins/Extended-2.0.1/vendor/composer/../../src/um-wpcli/src/Core.php): Failed to open stream: No such file or directory in .../wp-content/plugins/query-monitor/vendor/composer/ClassLoader.php on line 576`
Looks like a conflict with QueryMonitor

FTP rename of the 2.0.1 folder to get access to WP backend
Deactivated Query Monitor
Activation of 2.0.1 failed with error message
```
Warning: include(.../wp-content/plugins/Extended-2.0.1/vendor/composer/../../src/um-wpcli/src/Core.php): Failed to open stream: No such file or directory in .../wp-content/themes/neve/vendor/composer/ClassLoader.php on line 576

Warning: include(): Failed opening '.../wp-content/plugins/Extended-2.0.1/vendor/composer/../../src/um-wpcli/src/Core.php' for inclusion (include_path='.:/opt/alt/php82/usr/share/pear:/opt/alt/php82/usr/share/php:/usr/share/pear:/usr/share/php') in .../wp-content/themes/neve/vendor/composer/ClassLoader.php on line 576

Invalid Class Name: UM_WPCLI\Core
```

**Comment by champsupertramp** [comment]
Hi @MissVeronica - We've fixed the issue with the missing UM-WPCLI dependency, please see the latest alpha version:
https://github.com/ultimatemember/Extended/releases

**Comment by MissVeronica** [comment]
Thanks
UM Extended - 2.0.2-alpha.5 is OK now.
Tested deactivation of all Basic Extensions and made some activations.

**Comment by Phobos94** [comment]
Hello,
I finally solved the blank page problem when installing UM Extended. It was a conflict with the MonsterInsights - Google Analytics plugin. Once MonsterInsights - Google Analytics was disabled, the installation was ok and I had access to the UM Extended control panel.
I activated the "Browser Detect" plugin but the custom fields for IP, browser, etc... do not appear in the
When I try to install only the "Browser Detect" plugin, it tells me that it could not be installed due to a fatal error...

**Comment by champsupertramp** [comment]
Hi @MissVeronica  Thank you for the confirmation and your help. 

@Phobos94  - The Browser Detect extension only adds extra predefined fields to capture IP Address, Browser and Operating System of the clients in the UM Profile & Register forms.  Please see the screenshot below:
<img width="821" alt="Screenshot 2023-11-15 at 7 54 18 PM" src="https://github.com/ultimatemember/Extended/assets/12200688/8a29d91f-4369-4bef-995f-c6571e703311">
