### ISSUE TITLE
UM Extended: Fields Character and Words Counter

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#4]
### UM Extended Plugin Conflict: "Fields Character and Words Counter"

https://wordpress.org/support/topic/error-messages-missing/

**Comment by champsupertramp** [comment]
Closed by https://github.com/ultimatemember/Extended/commit/5dfd23549ebe7f999ed586076d3ab75d74ef7631

**Comment by yuriinalivaiko** [comment]
This issue has not been solved yet.

The `keyup` event function triggered on the document `ready` removes error messages that are not related to the _"Fields Character and Words Counter"_ extension.
