### ISSUE TITLE
Issues with Extended Features & Functionalities

### ISSUE THREAD

**Issue by NorSubs** [ultimatemember/Extended#40]
Hi.

I am trying to set up “Ultimate Member – Extended Features & Functionalities” by following the information at docs.ultimatemember.com;

1) https://docs.ultimatemember.com/article/1663-download-installation-of-the-basic-extensions

2) https://github.com/ultimatemember/Extended/releases/tag/2.0.0-beta2

3) https://docs.ultimatemember.com/article/1870-block-disposable-email-domains

But when activated, I am not able to find the “Blocked Disposable Email Domains” at Ultimate Member > Settings > Access > Other >

And I am still getting this message in Ultimate Member > Options > Secure: “You are not blocking email addresses or disposable email domains that are mostly used for Spam Account Registrations.”

Also the plugin does not show “Deactivate” when it is activated.

Please help.

BR
NorSubs

**Comment by champsupertramp** [comment]
Hi @NorSubs 

Please try the latest release in the link:
https://github.com/ultimatemember/Extended/releases/tag/2.0.0

Kindest Regards,

**Comment by champsupertramp** [comment]
Hi @NorSubs  Please see the latest release with fixes to this issue:
https://github.com/ultimatemember/Extended/releases
