### ISSUE TITLE
Developers Update Version Numbers

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#6]
Developers remember to update the version numbers when doing a change of the basic extension code snippets.

This time I used version 1.0.0 of the "Enable Profile Photo in Register form" until I found that my version 1.0.0 had less lines than the github version and both were version 1.0.0.

**Comment by champsupertramp** [comment]
Hi @MissVeronica  Thanks for letting us know. I've also just started adding changelog.txt to help everyone track the changes.

Kindest Regards,
