### ISSUE TITLE
Extended documentation links "Not Found"

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#68]
For example at this page https://docs.ultimatemember.com/article/1673-user-meta-shortcode

> 
> Overview
> 
> This plugin will enable you to add a shortcode functionality to render User Meta data in posts or pages. For the installation guide of this plugin, you can read it [here](https://docs.ultimatemember.com/article/1663-download-installation-of-the-basic-extensions).

Link from "here" is a  "Not Found" page.

**Comment by AngeliMae** [comment]
@champsupertramp Basic extension documents are updated.
