### ISSUE TITLE
"Invalid Class Name: UM_Extended_Set_Password\Core" after Install and enable all active

### ISSUE THREAD

**Issue by michael-feh** [ultimatemember/Extended#69]
I downloaded and installed the Extend-main plugin. I activated the part “set password for email” part.
Unfortunatelly it didnt have any effect: the {set_password_link} didnt output the desired link in the mail… this link in the mail after import was: “x-webdoc://A702DF8B-5471-4C95-9260-2490252761A3/%7Bset_password_link%7D”
(Same issue as https://github.com/ultimatemember/Extended/issues/22 i guess)

So i checked the plugin settings again and clicked on the “enable all active” switch. 
Since then i cannot enter the frontend or admin backend of the site but get the error message:
“Invalid Class Name: UM_Extended_Set_Password\Core”

I tried deactivating all other plugins and im running a standard theme “Twenty Twenty-Three”. PHP is 8.2.
I also updated to UM version 2.8.0 and I used the version before.

The only way to access the site again is by deleteing the plugin via ftp.

**Comment by champsupertramp** [comment]
Hi @michael-feh  - Are you using the Extended version in the link?
https://github.com/ultimatemember/Extended/releases/tag/2.0.3

**Comment by champsupertramp** [comment]
Hi @michael-feh  - I'm working on this issue now. I'll get back to you

**Comment by champsupertramp** [comment]
Hi @michael-feh  - please check the latest release: https://github.com/ultimatemember/Extended/releases

Let us know if you're still having issues.

**Comment by michael-feh** [comment]
Hey @champsupertramp ,

i downloaded the new version and installed it.
The error message is gone. I can use the plugin.

I'm still having issues with the set password link, but i will open a new ticket for this.

Thank you.
