### ISSUE TITLE
Outdated tests in "Enable Profile Photo in Register form"

### ISSUE THREAD

**Issue by MissVeronica** [ultimatemember/Extended#7]
All details including updated plugin code in this support thread:
https://wordpress.org/support/topic/profile-photo-in-registration/

**Comment by MissVeronica** [comment]
Support Forum issue:
https://wordpress.org/support/topic/profile-photo-not-showing-after-update/

**Comment by champsupertramp** [comment]
Closed by https://github.com/ultimatemember/Extended/pull/8/commits/064d7e8674a51cd73e2d82016a4cedfa2dc069e3
